---
- name: create boot volume
  os_volume:
    cloud: daou_cloud
    state: present
    size: 200
    display_name: "{{ item.name }}_vol_{{ item.dev_name }}"
    timeout: 300
    wait: yes
  with_items:
    - "{{ vm_volume }}"


- name: attach volume to host
  os_server_volume:
    state: present
    cloud: daou_cloud
    server: "{{ item.name }}"
    volume: "{{ item.name }}_vol_{{ item.dev_name }}"
  with_items:
    - "{{ vm_volume }}"
