---
- name: disable selinux
  lineinfile:
    line: 'SELINUX=disabled'
    regexp: '^SELINUX=enforcing'
    path: /etc/selinux/config
    state: present
    backrefs: yes
  register: disable_selinux

- name: selinux to permissive
  shell: setenforce 0
  ignore_errors: true

- name: install epel repository
  yum:
    name: epel-release
    state: latest

- name: install phoronix-test-suite packages
  yum:
   name: "{{ item }}"
   state: latest
  with_items:
    - phoronix-test-suite
    - docker
    - pcp-export-zabbix-agent.x86_64
    - python2-pip

- name: install zabbix-api
  pip:
    name: zabbix-api

- name : enable/start pmcd systemd
  systemd:
    name: pmcd
    enabled: yes
    state: started

- name : enable/start docker systemd
  systemd:
    name: docker 
    enabled: yes
    state: started


#- name: install docker compose
#  shell: 'sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'

- name : change mode
  shell : 'sudo chmod +x /usr/local/bin/docker-compose && sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose '
  ignore_errors: yes





