---
- name: install packages
  become: true
  hosts: vm

  tasks:

  - name: create a temp dir for stress to use
    file: path="{{ stress_tmp_dir }}" state=directory

  - name: run stress-ng
    command: >
      screen -S stress -d -m
      stress-ng
      --timeout {{ test_duration }}
      --cpu {{ cpu_workers }}
      --cpu-load {{ cpu_load }}
      --log-file {{ stress_tmp_dir }}/stress-ng-{{ ansible_date_time.iso8601_basic_short }}.log
      ; sleep 2
    args:
      chdir: "{{ stress_tmp_dir }}"
    tags: skip_ansible_lint
    
  - name: get stress-ng process count
    shell: ps -ef|grep "[s]tress-ng"|wc -l
    register: stress_procs
    changed_when: False
    check_mode: False
    tags: skip_ansible_lint

  - name: fail if no stress-ng processes found
    fail:
      msg: No stress-ng processes found!
    when: stress_procs.stdout < 1

  - name: get dead screen count
    shell: screen -ls|grep -c Dead
    register: reg_dead_screens
    changed_when: False
    check_mode: False
    failed_when: False
    tags: skip_ansible_lint

  - name: fail if there are dead screens
    fail:
      msg: Found dead screens. stress-ng probably did not start. Run screen -wipe and try again.
    when: reg_dead_screens.stdout|int > 0
